### PR TITLE
fix(TimePicker): call onChange callback when new time is typed

### LINKED ISSUE #171: Timepicker does not call onChange callback when the time is changed by typing
The time is set in the local state of the TimePicker, so it shows up correctly. The problem is it never calls the onChange callback because it never calls the "triggerOnChange" function.

### PR DESCRIPTION
**Pull request by cruzj6**
Fixes #171 
Call triggerOnChange when setting the time directly by typing.

### CODE REVIEW

**Comment by cruzj6** [comment]
@pauljeter I added UTs, but I'm a bit unsure of the intent of the 'dayChage' parameter that is passed to the callback. The logic says if the new time (when hour/minute is changed) is before today, return -1, if it is after return 1, otherwise return 0. The issue is today might not have been the starting time, as is the case in the UTs. Maybe that's intended? Want to make sure the UTs are validating it correctly and it's not a bug.

Here is the code in question:
```
    const newTime = moment(this.state.selectedTime).add(change, unit);
    let dayChange = 0;

    if (change >= 0) {
      if (
        newTime
          .clone()
          .startOf('day')
          .isAfter(moment().startOf('day'))
      ) {
        newTime.add(-1, 'day');
        dayChange = 1;
      }
    } else {
      if (
        newTime
          .clone()
          .startOf('day')
          .isBefore(moment().startOf('day'))
      ) {
        newTime.add(1, 'day');
        dayChange = -1;
      }
    }

    this.setState({ selectedTime: newTime }, () => this.triggerOnChange(dayChange));
```

**Comment by bfbiggs** [comment]
> @pauljeter I added UTs, but I'm a bit unsure of the intent of the 'dayChage' parameter that is passed to the callback. The logic says if the new time (when hour/minute is changed) is before today, return -1, if it is after return 1, otherwise return 0. The issue is today might not have been the starting time, as is the case in the UTs. Maybe that's intended? It also goes and changes the newTime's day back to today, so the day doesn't actually change when the state is set. Want to make sure the UTs are validating it correctly and it's not a bug.
> 
> Here is the code in question:
> 
> ```
>     const newTime = moment(this.state.selectedTime).add(change, unit);
>     let dayChange = 0;
> 
>     if (change >= 0) {
>       if (
>         newTime
>           .clone()
>           .startOf('day')
>           .isAfter(moment().startOf('day'))
>       ) {
>         newTime.add(-1, 'day');
>         dayChange = 1;
>       }
>     } else {
>       if (
>         newTime
>           .clone()
>           .startOf('day')
>           .isBefore(moment().startOf('day'))
>       ) {
>         newTime.add(1, 'day');
>         dayChange = -1;
>       }
>     }
> 
>     this.setState({ selectedTime: newTime }, () => this.triggerOnChange(dayChange));
> ```

The day change is only mean for when using the up/down keys because it signifies you are passing the current day just in case the app wanted to keep track of that visually somewhere.  If the number is being typed in - it is impossible to know if the user meant forward/backward so @pauljeter and I both agreed that your implementation of calling the triggerOnChange with a 0 was correct.

**Comment by cruzj6** [comment]
> moment().startOf('day')

But doesn't this break if `selectedTime` was initialized as a specific date that is not the current day? You can pass a custom selected time prop that is used as the initial value for `selectedTime`? If I'm wrong and it's working as intended this PR should be good to go :P

**Comment by cruzj6** [comment]
@bfbiggs @pauljeter not sure if you saw my last comment, just want some clarification. Thanks!

**Pull request merged**
